### ISSUE TITLE
New Start Advanced, Locals spawning beneath map.

### ISSUE THREAD

**Issue by MasterRainwater** [CompletelyFairGames/dwarfcorp#587]
![20180322034717_1](https://user-images.githubusercontent.com/34499136/37766276-7a547cc2-2d94-11e8-8d91-62c198a4537e.jpg)

they dont pop up on the info on the bottom right and every local continually creeps towards one corner everytime you change something until you regen

**Comment by com1clyf3** [comment]
Still getting this on Version 478be122

**Comment by com1clyf3** [comment]
Still occurring on cf2d71db

**Comment by com1clyf3** [comment]
Still occurring on 126d7ff8

![image](https://user-images.githubusercontent.com/6562812/39726172-31b61078-521c-11e8-9cfd-2d8e7147c5b6.png)

any progress on this @mklingen ?

**Comment by mklingen** [comment]
Haven't investigated. I still am not sure what is meant by this bug.

**Comment by com1clyf3** [comment]
Pretty simple repro:
1. Start new game advanced.
2. Go to advanced settings. 
3. Change the natives settings. Easiest to see this bug  is to set it to high.
4. Do it once, and observe natives are headed to corner of map.
5. Do it again, and observe they're now all in the corner and some may even be floating off the map (like some of the icons in the image above in the bottom right corner)

**Comment by mklingen** [comment]
Oh so this always happens, and only happens when changing the settings?

**Comment by mklingen** [comment]
Ok will fix.

**Comment by mklingen** [comment]
Fixed in master. Cause was that old factions weren't getting cleaned up when settings were changed.

**Comment by com1clyf3** [comment]
This bug came back. 
![image](https://user-images.githubusercontent.com/6562812/45454226-23269d80-b6b1-11e8-8b1e-6486e1c1683a.png)

This does not repro every time, but when it does it tends to be this pattern:
1. Advanced game
2. Set advanced settings to very high for world size and natives.

World seen above can be found here: 
[Tubland.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2376929/Tubland.zip)

0c9a7de8
