### ISSUE TITLE
XNA: art stops rendering when paused and clicked out of screen

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#692]
**5/29/18 - This is being changed to a tracking issue for anything related to the XNA minimizing issue.**

![image](https://user-images.githubusercontent.com/6562812/39726991-f5f46816-521e-11e8-90b2-0f34c39fae1c.png)

When you click back into a paused minimized window, the terrain and sprites are gone.  You can fix this by going up or down a slice, but the sprites will still be missing, along with preview art for lots of build features.

1.Start game in window.
2. Pause game.
3. Click out of game and do something for a minute or two.
4. Click back into game. Observe missing terrain and sprites.
5. Change the slices to observe terrain pop in.

126d7ff8

**Comment by mklingen** [comment]
I was able to reproduce, and it seems to be more of the same garbage we've seen recently with the graphics device getting rebuilt causing all of our textures to get disposed simultaneously. Slicing the terrain has the effect of rebuilding the geometry.

I tried to reproduce this in FNA and was unable to do so.

I recommend as an emergency stopgap for this and other issues, we should take the plunge and abandon the XNA build and start distributing FNA builds only.

**Comment by mklingen** [comment]
As far as I can tell, I've fixed this bug in XNA. Again it may be better to just go to FNA soon.

**Comment by com1clyf3** [comment]
Still occurring in 5fee6751

**Comment by mklingen** [comment]
This should be fixed.

**Comment by com1clyf3** [comment]
XNA issues still occurring on 236e5063

![image](https://user-images.githubusercontent.com/6562812/42185553-516695ba-7e17-11e8-9d8e-6623454518dd.png)

**Comment by Blecki** [comment]
This is because objects don't update when paused. Fixing is likely more work than is worth it right now.

**Comment by mklingen** [comment]
@Blecki actually this is still the same nasty bug rearing its head again. When the composite gets disposed, we need to regenerate (invalidate) all of the composite animations.

**Comment by com1clyf3** [comment]
This get fixed?

**Comment by com1clyf3** [comment]
![image](https://user-images.githubusercontent.com/6562812/44934591-71e04900-ad3b-11e8-95ef-3e7f4a91abad.png)

Still occurs on 5bd9f3c4

**Comment by com1clyf3** [comment]
Why? This is a huge bug.

**Comment by com1clyf3** [comment]
![image](https://user-images.githubusercontent.com/6562812/45183470-2e318780-b1f2-11e8-9eba-5c6ebfd22c15.png)

Still occurring in a6e468d2

**Comment by com1clyf3** [comment]
Confirmed only happening in XNA, so closing.
