### ISSUE TITLE
Trade: Crash after canceling out of trade menu  - System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#753]
1. Open game
2. Send trade envoy
3. Trade something successfully
4. Press cancel
5. Observe crash to desktop.

Might have to give this a couple of tries, but repros most of the time.

[201805291539103033_Crashlog.txt](https://github.com/CompletelyFairGames/dwarfcorp/files/2050443/201805291539103033_Crashlog.txt)
[201805291538037793_Crashlog.txt](https://github.com/CompletelyFairGames/dwarfcorp/files/2050444/201805291538037793_Crashlog.txt)

5c6a30a6

**Comment by mklingen** [comment]
Fixed in master.

**Comment by com1clyf3** [comment]
This still occurs in 2cc387dd . It doesn't happen every time however, so it's improved.


[201805301241099788_Crashlog.txt](https://github.com/CompletelyFairGames/dwarfcorp/files/2054846/201805301241099788_Crashlog.txt)

**Comment by mklingen** [comment]
Was unable to reproduce... will try again.

**Comment by com1clyf3** [comment]
Might want to try canceling when the successful trade message overlaps the trade menu. Since it's a new feature, I'm guessing it's a likely culprit.

**Comment by mklingen** [comment]
Fixed in master.
