### ISSUE TITLE
Economy: Player stuck on trade screen after proposing empty trade

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#818]
Likely an outcome of fixing #782 

1. Enter trade event.
2. Propose an empty trade.
3. Then try anything to exit trade menu from performing a successful trade to just canceling trade.
4. Observe player is stuck in trade menu and forced to quit game.

1fb82458

**Comment by Blecki** [comment]
Wasn't able to reproduce. Did you do anything else before proposing the empty trade? What race was the trader?

**Comment by com1clyf3** [comment]
Not race specific. Works with both elves, goblins, and dwarves at least.  Tried a completely new game and still repros.  Tried both windowed and fullscreen, and a few other things. Everything I've done so far causes a repro. Just propose the empty trade. If you want I can make a vid of it happening.

**Comment by mklingen** [comment]
Can't reproduce. I think this must have been fixed already while fixing something else?

**Comment by com1clyf3** [comment]
This is still occurring on b8d13dd8 exactly as described. Make sure you're playing master branch?

**Comment by com1clyf3** [comment]
Looks like we might have a lead here: https://steamcommunity.com/app/252390/discussions/0/1737715419891192414/

Going to try out a repro with this.

**Comment by Blecki** [comment]
Problem was the invisible container for the dialogue choice menu was 'on top' and sucking up all mouse events.

**Comment by mklingen** [comment]
@Blecki was this fixed by making the container smaller, or something else?
