### ISSUE TITLE
AI: "Air humping" - Dwarves getting stuck in pathing loops

### ISSUE THREAD

**Issue by com1clyf3** [CompletelyFairGames/dwarfcorp#846]
https://steamcommunity.com/app/252390/discussions/1/1692669912390094558/

[Secretaryland_480_131813429616057161.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2380860/Secretaryland_480_131813429616057161.zip)
[Secretaryland.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2380852/Secretaryland.zip)

See Steam thread above. Looks like they're experiencing more and more pathing loops from crafters, the farther they play into the game. I've requested they send us a save. Not exactly sure what they're experiencing, but I've observed a pattern of bug I've been trying to suss out that sounds familiar. Not 100% on the repro, but this is usually how it occurs:

1. (I usually use cooking, but I'm guessing any repeatable craft works) Set a repeatable task, like 10x cooking meals.
2. After the Crafter is done, set another 10x crafting meals.
3. Observe the Crafter eventually become stuck on a few voxels jumping back and forth (the "humping" I think the player is referencing)
4. Eventually they'll become unstuck form this behavior, but then eventually caught in a new loop, pathing back and forth between the crafting station and another location, usually a stockpile. The task will still be to cook, but the Crafter seems unable to collect the required resources for some reason. Canceling the task resolves the bug.

1299186a

**Comment by mklingen** [comment]
I believe I have fixed the root cause of this issue by accident while developing palisades. Will test this save to see if I can reproduce it.

**Comment by mklingen** [comment]
okay, I believe I have fixed this, and that save does not currently have the problem.

Forensics:
1. When crafting multiple items, and "Any" is selected as an ingredient, the dwarf assigns random goods from your stockpile to be the source of the item. 
2. If the crafting gets interrupted, it gets put back on the task queue with those selected ingredients.
3. If those ingredients are no longer present for whatever reason (maybe another dwarf ate them), the dwarf believes the resources are available, but they are in fact unavailable.
4. When the dwarf arrives at the crafting station, it believes that it has the resources already, but when it looks in its backpack, it finds the resources to be missing.

I fixed this by making the crafting task clean up after itself on failure, and made the dwarf check the contents of its backpack to be extra sure that it has the resources before attempting to craft.

**Comment by com1clyf3** [comment]
Still seeing this behavior: 

> Observe the Crafter eventually become stuck on a few voxels jumping back and forth (the "humping" I think the player is referencing)

in 233bc5a8

It's not exclusive to crafters.

**Comment by com1clyf3** [comment]
Here's an example:
[Important Hills_386_131822986041129880.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2412983/Important.Hills_386_131822986041129880.zip)
[Important Hills.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2412984/Important.Hills.zip)

**Comment by mklingen** [comment]
That example doesn't seem to have the problem you're describing...

**Comment by mklingen** [comment]
although it does have a ton of other problems mainly with pathfinding, which is pretty baffling

**Comment by com1clyf3** [comment]
>While "taking a walk" dwarfs were sometimes jumping up and down on the same spot over and over. Prevented this.

Thems the humps, so it's fixed.

**Comment by com1clyf3** [comment]
This is still occurring on b089ea7a


![image](https://user-images.githubusercontent.com/6562812/46978077-e6790800-d09b-11e8-9ec2-6927080f4354.png)


[Bead Realm_53_131841106693600935.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2480535/Bead.Realm_53_131841106693600935.zip)
[Bead Realm.zip](https://github.com/CompletelyFairGames/dwarfcorp/files/2480536/Bead.Realm.zip)
